language: go
os: 
  - linux
  - osx
dist: trusty

go:
  - 1.6.3
addons:
  apt:
    packages:
    - libvirt-bin
    - libvirt-dev
env:
  - GOARCH=amd64
sudo: false
before_install:
  - go get -u github.com/kardianos/govendor
script:
  - govendor sync
  - go test
  - cd main && go build -o zvirt-agent && cd -
  - mvn -B deploy  --settings support/settings.xml
notifications:
  email: false
