// Code generated by protoc-gen-go.
// source: zvirt_domain.proto
// DO NOT EDIT!

/*
Package protocol is a generated protocol buffer package.

It is generated from these files:
	zvirt_domain.proto

It has these top-level messages:
	DomStateRequest
	DomStateResponse
*/
package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// domain state
type DomainState int32

const (
	DomainState_VIR_DOMAIN_NOSTATE     DomainState = 0
	DomainState_VIR_DOMAIN_RUNNING     DomainState = 1
	DomainState_VIR_DOMAIN_BLOCKED     DomainState = 2
	DomainState_VIR_DOMAIN_PAUSED      DomainState = 3
	DomainState_VIR_DOMAIN_SHUTDOWN    DomainState = 4
	DomainState_VIR_DOMAIN_SHUTOFF     DomainState = 5
	DomainState_VIR_DOMAIN_CRASHED     DomainState = 6
	DomainState_VIR_DOMAIN_PMSUSPENDED DomainState = 7
	DomainState_VIR_DOMAIN_LAST        DomainState = 8
)

var DomainState_name = map[int32]string{
	0: "VIR_DOMAIN_NOSTATE",
	1: "VIR_DOMAIN_RUNNING",
	2: "VIR_DOMAIN_BLOCKED",
	3: "VIR_DOMAIN_PAUSED",
	4: "VIR_DOMAIN_SHUTDOWN",
	5: "VIR_DOMAIN_SHUTOFF",
	6: "VIR_DOMAIN_CRASHED",
	7: "VIR_DOMAIN_PMSUSPENDED",
	8: "VIR_DOMAIN_LAST",
}
var DomainState_value = map[string]int32{
	"VIR_DOMAIN_NOSTATE":     0,
	"VIR_DOMAIN_RUNNING":     1,
	"VIR_DOMAIN_BLOCKED":     2,
	"VIR_DOMAIN_PAUSED":      3,
	"VIR_DOMAIN_SHUTDOWN":    4,
	"VIR_DOMAIN_SHUTOFF":     5,
	"VIR_DOMAIN_CRASHED":     6,
	"VIR_DOMAIN_PMSUSPENDED": 7,
	"VIR_DOMAIN_LAST":        8,
}

func (x DomainState) String() string {
	return proto.EnumName(DomainState_name, int32(x))
}
func (DomainState) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// domain stat request
type DomStateRequest struct {
	VmId string `protobuf:"bytes,1,opt,name=vm_id,json=vmId" json:"vm_id,omitempty"`
}

func (m *DomStateRequest) Reset()                    { *m = DomStateRequest{} }
func (m *DomStateRequest) String() string            { return proto.CompactTextString(m) }
func (*DomStateRequest) ProtoMessage()               {}
func (*DomStateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *DomStateRequest) GetVmId() string {
	if m != nil {
		return m.VmId
	}
	return ""
}

type DomStateResponse struct {
	State DomainState `protobuf:"varint,1,opt,name=state,enum=protocol.DomainState" json:"state,omitempty"`
}

func (m *DomStateResponse) Reset()                    { *m = DomStateResponse{} }
func (m *DomStateResponse) String() string            { return proto.CompactTextString(m) }
func (*DomStateResponse) ProtoMessage()               {}
func (*DomStateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DomStateResponse) GetState() DomainState {
	if m != nil {
		return m.State
	}
	return DomainState_VIR_DOMAIN_NOSTATE
}

func init() {
	proto.RegisterType((*DomStateRequest)(nil), "protocol.DomStateRequest")
	proto.RegisterType((*DomStateResponse)(nil), "protocol.DomStateResponse")
	proto.RegisterEnum("protocol.DomainState", DomainState_name, DomainState_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ZvirtDomainService service

type ZvirtDomainServiceClient interface {
	DomState(ctx context.Context, in *DomStateRequest, opts ...grpc.CallOption) (*DomStateResponse, error)
}

type zvirtDomainServiceClient struct {
	cc *grpc.ClientConn
}

func NewZvirtDomainServiceClient(cc *grpc.ClientConn) ZvirtDomainServiceClient {
	return &zvirtDomainServiceClient{cc}
}

func (c *zvirtDomainServiceClient) DomState(ctx context.Context, in *DomStateRequest, opts ...grpc.CallOption) (*DomStateResponse, error) {
	out := new(DomStateResponse)
	err := grpc.Invoke(ctx, "/protocol.ZvirtDomainService/DomState", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ZvirtDomainService service

type ZvirtDomainServiceServer interface {
	DomState(context.Context, *DomStateRequest) (*DomStateResponse, error)
}

func RegisterZvirtDomainServiceServer(s *grpc.Server, srv ZvirtDomainServiceServer) {
	s.RegisterService(&_ZvirtDomainService_serviceDesc, srv)
}

func _ZvirtDomainService_DomState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DomStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZvirtDomainServiceServer).DomState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.ZvirtDomainService/DomState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZvirtDomainServiceServer).DomState(ctx, req.(*DomStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ZvirtDomainService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protocol.ZvirtDomainService",
	HandlerType: (*ZvirtDomainServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DomState",
			Handler:    _ZvirtDomainService_DomState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "zvirt_domain.proto",
}

func init() { proto.RegisterFile("zvirt_domain.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 312 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x91, 0xc1, 0x4e, 0xf2, 0x40,
	0x14, 0x85, 0xe9, 0xff, 0x03, 0xe2, 0x35, 0x81, 0xf1, 0x12, 0x50, 0x59, 0x19, 0x62, 0x8c, 0xd1,
	0x84, 0x05, 0x3e, 0x80, 0x29, 0xcc, 0x20, 0x8d, 0x30, 0x6d, 0x3a, 0xad, 0x46, 0x37, 0x0d, 0xc2,
	0x2c, 0x9a, 0x58, 0x06, 0x69, 0xed, 0xc2, 0x07, 0xf6, 0x39, 0x4c, 0x5b, 0xd1, 0xb1, 0x71, 0xd5,
	0xe4, 0x3b, 0x27, 0xe7, 0xa6, 0xdf, 0x00, 0xbe, 0xa7, 0xe1, 0x36, 0x09, 0x56, 0x2a, 0x5a, 0x84,
	0xeb, 0xc1, 0x66, 0xab, 0x12, 0x85, 0x8d, 0xfc, 0xb3, 0x54, 0x2f, 0xfd, 0x73, 0x68, 0x51, 0x15,
	0x89, 0x64, 0x91, 0x48, 0x57, 0xbe, 0xbe, 0xc9, 0x38, 0xc1, 0x36, 0xd4, 0xd2, 0x28, 0x08, 0x57,
	0xc7, 0xc6, 0xa9, 0x71, 0xb1, 0xef, 0x56, 0xd3, 0xc8, 0x5a, 0xf5, 0x6f, 0x80, 0xfc, 0xf4, 0xe2,
	0x8d, 0x5a, 0xc7, 0x12, 0xaf, 0xa0, 0x16, 0x67, 0x20, 0x2f, 0x36, 0x87, 0x9d, 0xc1, 0x6e, 0x75,
	0x40, 0xf3, 0x63, 0x45, 0xbb, 0xe8, 0x5c, 0x7e, 0x18, 0x70, 0xa0, 0x61, 0xec, 0x02, 0xde, 0x5b,
	0x6e, 0x40, 0xed, 0xb9, 0x69, 0xf1, 0x80, 0xdb, 0xc2, 0x33, 0x3d, 0x46, 0x2a, 0x25, 0xee, 0xfa,
	0x9c, 0x5b, 0xfc, 0x96, 0x18, 0x25, 0x3e, 0x9a, 0xd9, 0xe3, 0x3b, 0x46, 0xc9, 0x3f, 0xec, 0xc0,
	0xa1, 0xc6, 0x1d, 0xd3, 0x17, 0x8c, 0x92, 0xff, 0x78, 0x04, 0x6d, 0x0d, 0x8b, 0xa9, 0xef, 0x51,
	0xfb, 0x81, 0x93, 0x6a, 0x69, 0x27, 0x0b, 0xec, 0xc9, 0x84, 0xd4, 0x4a, 0x7c, 0xec, 0x9a, 0x62,
	0xca, 0x28, 0xa9, 0x63, 0x0f, 0xba, 0xfa, 0xfe, 0x5c, 0xf8, 0xc2, 0x61, 0x9c, 0x32, 0x4a, 0xf6,
	0xb0, 0x0d, 0x2d, 0x2d, 0x9b, 0x99, 0xc2, 0x23, 0x8d, 0xe1, 0x23, 0xe0, 0x53, 0x66, 0xfc, 0xeb,
	0x67, 0xe5, 0x36, 0x0d, 0x97, 0x12, 0xc7, 0xd0, 0xd8, 0xf9, 0xc3, 0x93, 0x5f, 0xa2, 0x74, 0xf7,
	0xbd, 0xde, 0x5f, 0x51, 0xa1, 0xbb, 0x5f, 0x19, 0x9d, 0x41, 0x33, 0x7f, 0xcc, 0xef, 0xd2, 0x88,
	0x68, 0xa7, 0x9c, 0x0c, 0x3a, 0xc6, 0x73, 0x3d, 0x4f, 0xaf, 0x3f, 0x03, 0x00, 0x00, 0xff, 0xff,
	0x3f, 0x26, 0xaf, 0x16, 0xf9, 0x01, 0x00, 0x00,
}
