// Code generated by protoc-gen-go.
// source: zvirt_domain.proto
// DO NOT EDIT!

/*
Package protocol is a generated protocol buffer package.

It is generated from these files:
	zvirt_domain.proto
	zvirt_pool.proto
	zvirt_volume.proto

It has these top-level messages:
	DomainUUID
	DomainDefineRequest
	DomainStateResponse
	PoolUUID
	PoolDefineRequest
	PoolStateResponse
	VolumeDefineRequest
	VolumeRequest
	VolumeInfo
*/
package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// domain state
type DomainState int32

const (
	DomainState_VIR_DOMAIN_NOSTATE     DomainState = 0
	DomainState_VIR_DOMAIN_RUNNING     DomainState = 1
	DomainState_VIR_DOMAIN_BLOCKED     DomainState = 2
	DomainState_VIR_DOMAIN_PAUSED      DomainState = 3
	DomainState_VIR_DOMAIN_SHUTDOWN    DomainState = 4
	DomainState_VIR_DOMAIN_SHUTOFF     DomainState = 5
	DomainState_VIR_DOMAIN_CRASHED     DomainState = 6
	DomainState_VIR_DOMAIN_PMSUSPENDED DomainState = 7
	DomainState_VIR_DOMAIN_LAST        DomainState = 8
)

var DomainState_name = map[int32]string{
	0: "VIR_DOMAIN_NOSTATE",
	1: "VIR_DOMAIN_RUNNING",
	2: "VIR_DOMAIN_BLOCKED",
	3: "VIR_DOMAIN_PAUSED",
	4: "VIR_DOMAIN_SHUTDOWN",
	5: "VIR_DOMAIN_SHUTOFF",
	6: "VIR_DOMAIN_CRASHED",
	7: "VIR_DOMAIN_PMSUSPENDED",
	8: "VIR_DOMAIN_LAST",
}
var DomainState_value = map[string]int32{
	"VIR_DOMAIN_NOSTATE":     0,
	"VIR_DOMAIN_RUNNING":     1,
	"VIR_DOMAIN_BLOCKED":     2,
	"VIR_DOMAIN_PAUSED":      3,
	"VIR_DOMAIN_SHUTDOWN":    4,
	"VIR_DOMAIN_SHUTOFF":     5,
	"VIR_DOMAIN_CRASHED":     6,
	"VIR_DOMAIN_PMSUSPENDED": 7,
	"VIR_DOMAIN_LAST":        8,
}

func (x DomainState) String() string {
	return proto.EnumName(DomainState_name, int32(x))
}
func (DomainState) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type DomainUUID struct {
	Uuid string `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
}

func (m *DomainUUID) Reset()                    { *m = DomainUUID{} }
func (m *DomainUUID) String() string            { return proto.CompactTextString(m) }
func (*DomainUUID) ProtoMessage()               {}
func (*DomainUUID) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *DomainUUID) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type DomainDefineRequest struct {
	Xml string `protobuf:"bytes,1,opt,name=xml" json:"xml,omitempty"`
}

func (m *DomainDefineRequest) Reset()                    { *m = DomainDefineRequest{} }
func (m *DomainDefineRequest) String() string            { return proto.CompactTextString(m) }
func (*DomainDefineRequest) ProtoMessage()               {}
func (*DomainDefineRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DomainDefineRequest) GetXml() string {
	if m != nil {
		return m.Xml
	}
	return ""
}

type DomainStateResponse struct {
	State DomainState `protobuf:"varint,1,opt,name=state,enum=protocol.DomainState" json:"state,omitempty"`
}

func (m *DomainStateResponse) Reset()                    { *m = DomainStateResponse{} }
func (m *DomainStateResponse) String() string            { return proto.CompactTextString(m) }
func (*DomainStateResponse) ProtoMessage()               {}
func (*DomainStateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *DomainStateResponse) GetState() DomainState {
	if m != nil {
		return m.State
	}
	return DomainState_VIR_DOMAIN_NOSTATE
}

func init() {
	proto.RegisterType((*DomainUUID)(nil), "protocol.DomainUUID")
	proto.RegisterType((*DomainDefineRequest)(nil), "protocol.DomainDefineRequest")
	proto.RegisterType((*DomainStateResponse)(nil), "protocol.DomainStateResponse")
	proto.RegisterEnum("protocol.DomainState", DomainState_name, DomainState_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ZvirtDomainService service

type ZvirtDomainServiceClient interface {
	Domstate(ctx context.Context, in *DomainUUID, opts ...grpc.CallOption) (*DomainStateResponse, error)
	Define(ctx context.Context, in *DomainDefineRequest, opts ...grpc.CallOption) (*DomainUUID, error)
	Start(ctx context.Context, in *DomainUUID, opts ...grpc.CallOption) (*DomainStateResponse, error)
	Shutdown(ctx context.Context, in *DomainUUID, opts ...grpc.CallOption) (*DomainStateResponse, error)
	Destroy(ctx context.Context, in *DomainUUID, opts ...grpc.CallOption) (*DomainStateResponse, error)
}

type zvirtDomainServiceClient struct {
	cc *grpc.ClientConn
}

func NewZvirtDomainServiceClient(cc *grpc.ClientConn) ZvirtDomainServiceClient {
	return &zvirtDomainServiceClient{cc}
}

func (c *zvirtDomainServiceClient) Domstate(ctx context.Context, in *DomainUUID, opts ...grpc.CallOption) (*DomainStateResponse, error) {
	out := new(DomainStateResponse)
	err := grpc.Invoke(ctx, "/protocol.ZvirtDomainService/domstate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zvirtDomainServiceClient) Define(ctx context.Context, in *DomainDefineRequest, opts ...grpc.CallOption) (*DomainUUID, error) {
	out := new(DomainUUID)
	err := grpc.Invoke(ctx, "/protocol.ZvirtDomainService/define", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zvirtDomainServiceClient) Start(ctx context.Context, in *DomainUUID, opts ...grpc.CallOption) (*DomainStateResponse, error) {
	out := new(DomainStateResponse)
	err := grpc.Invoke(ctx, "/protocol.ZvirtDomainService/start", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zvirtDomainServiceClient) Shutdown(ctx context.Context, in *DomainUUID, opts ...grpc.CallOption) (*DomainStateResponse, error) {
	out := new(DomainStateResponse)
	err := grpc.Invoke(ctx, "/protocol.ZvirtDomainService/shutdown", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zvirtDomainServiceClient) Destroy(ctx context.Context, in *DomainUUID, opts ...grpc.CallOption) (*DomainStateResponse, error) {
	out := new(DomainStateResponse)
	err := grpc.Invoke(ctx, "/protocol.ZvirtDomainService/destroy", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ZvirtDomainService service

type ZvirtDomainServiceServer interface {
	Domstate(context.Context, *DomainUUID) (*DomainStateResponse, error)
	Define(context.Context, *DomainDefineRequest) (*DomainUUID, error)
	Start(context.Context, *DomainUUID) (*DomainStateResponse, error)
	Shutdown(context.Context, *DomainUUID) (*DomainStateResponse, error)
	Destroy(context.Context, *DomainUUID) (*DomainStateResponse, error)
}

func RegisterZvirtDomainServiceServer(s *grpc.Server, srv ZvirtDomainServiceServer) {
	s.RegisterService(&_ZvirtDomainService_serviceDesc, srv)
}

func _ZvirtDomainService_Domstate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DomainUUID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZvirtDomainServiceServer).Domstate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.ZvirtDomainService/Domstate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZvirtDomainServiceServer).Domstate(ctx, req.(*DomainUUID))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZvirtDomainService_Define_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DomainDefineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZvirtDomainServiceServer).Define(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.ZvirtDomainService/Define",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZvirtDomainServiceServer).Define(ctx, req.(*DomainDefineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZvirtDomainService_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DomainUUID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZvirtDomainServiceServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.ZvirtDomainService/Start",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZvirtDomainServiceServer).Start(ctx, req.(*DomainUUID))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZvirtDomainService_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DomainUUID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZvirtDomainServiceServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.ZvirtDomainService/Shutdown",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZvirtDomainServiceServer).Shutdown(ctx, req.(*DomainUUID))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZvirtDomainService_Destroy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DomainUUID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZvirtDomainServiceServer).Destroy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.ZvirtDomainService/Destroy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZvirtDomainServiceServer).Destroy(ctx, req.(*DomainUUID))
	}
	return interceptor(ctx, in, info, handler)
}

var _ZvirtDomainService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protocol.ZvirtDomainService",
	HandlerType: (*ZvirtDomainServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "domstate",
			Handler:    _ZvirtDomainService_Domstate_Handler,
		},
		{
			MethodName: "define",
			Handler:    _ZvirtDomainService_Define_Handler,
		},
		{
			MethodName: "start",
			Handler:    _ZvirtDomainService_Start_Handler,
		},
		{
			MethodName: "shutdown",
			Handler:    _ZvirtDomainService_Shutdown_Handler,
		},
		{
			MethodName: "destroy",
			Handler:    _ZvirtDomainService_Destroy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "zvirt_domain.proto",
}

func init() { proto.RegisterFile("zvirt_domain.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 381 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x92, 0x4d, 0xcf, 0xd2, 0x40,
	0x1c, 0xc4, 0xe9, 0xf3, 0xf0, 0x52, 0xff, 0x26, 0xb8, 0xfe, 0x11, 0x34, 0x24, 0x26, 0xa4, 0x31,
	0xd1, 0x68, 0xc2, 0x01, 0xef, 0x6a, 0xcb, 0x16, 0x69, 0x84, 0xb6, 0xe9, 0xb6, 0x9a, 0x78, 0x21,
	0x48, 0xd7, 0xd8, 0x04, 0xba, 0xd8, 0x6e, 0xf1, 0xe5, 0xbb, 0x7a, 0xf5, 0x73, 0x98, 0x2e, 0x60,
	0x6a, 0xe5, 0xc4, 0xa9, 0x9b, 0x99, 0x5f, 0xa6, 0xed, 0xcc, 0x02, 0xfe, 0x3c, 0x24, 0x99, 0x5c,
	0xc5, 0x62, 0xb7, 0x4e, 0xd2, 0xf1, 0x3e, 0x13, 0x52, 0xa0, 0xae, 0x1e, 0x1b, 0xb1, 0x35, 0x46,
	0x00, 0x54, 0x39, 0x51, 0xe4, 0x50, 0x44, 0x68, 0x16, 0x45, 0x12, 0x3f, 0xd2, 0x46, 0xda, 0xb3,
	0x3b, 0x81, 0x3a, 0x1b, 0x4f, 0xa1, 0x77, 0x24, 0x28, 0xff, 0x9c, 0xa4, 0x3c, 0xe0, 0x5f, 0x0b,
	0x9e, 0x4b, 0x24, 0x70, 0xfb, 0x7d, 0xb7, 0x3d, 0x91, 0xe5, 0xd1, 0xb0, 0xce, 0x20, 0x93, 0x6b,
	0xc9, 0x03, 0x9e, 0xef, 0x45, 0x9a, 0x73, 0x7c, 0x01, 0xad, 0xbc, 0x14, 0x14, 0xda, 0x9d, 0xf4,
	0xc7, 0xe7, 0x77, 0x8f, 0xab, 0xf4, 0x91, 0x79, 0xfe, 0x5b, 0x83, 0xbb, 0x15, 0x19, 0x07, 0x80,
	0xef, 0x9d, 0x60, 0x45, 0xbd, 0xa5, 0xe9, 0xb8, 0x2b, 0xd7, 0x63, 0xa1, 0x19, 0xda, 0xa4, 0x51,
	0xd3, 0x83, 0xc8, 0x75, 0x1d, 0xf7, 0x2d, 0xd1, 0x6a, 0xba, 0xb5, 0xf0, 0xa6, 0xef, 0x6c, 0x4a,
	0x6e, 0xb0, 0x0f, 0xf7, 0x2b, 0xba, 0x6f, 0x46, 0xcc, 0xa6, 0xe4, 0x16, 0x1f, 0x42, 0xaf, 0x22,
	0xb3, 0x79, 0x14, 0x52, 0xef, 0x83, 0x4b, 0x9a, 0xb5, 0x9c, 0xd2, 0xf0, 0x66, 0x33, 0xd2, 0xaa,
	0xe9, 0xd3, 0xc0, 0x64, 0x73, 0x9b, 0x92, 0x36, 0x0e, 0x61, 0x50, 0xcd, 0x5f, 0xb2, 0x88, 0xf9,
	0xb6, 0x4b, 0x6d, 0x4a, 0x3a, 0xd8, 0x83, 0x7b, 0x15, 0x6f, 0x61, 0xb2, 0x90, 0xe8, 0x93, 0x5f,
	0x37, 0x80, 0x1f, 0xcb, 0x61, 0x4e, 0x7f, 0xcb, 0xb3, 0x43, 0xb2, 0xe1, 0x68, 0x82, 0x1e, 0x8b,
	0x9d, 0xea, 0x02, 0x1f, 0xd4, 0x9b, 0x2a, 0x27, 0x1a, 0x3e, 0xbe, 0xdc, 0xdf, 0xa9, 0x6d, 0xa3,
	0x81, 0xaf, 0xa1, 0x1d, 0xab, 0xa5, 0xf0, 0x3f, 0xf4, 0x9f, 0x05, 0x87, 0x17, 0xf3, 0x8d, 0x06,
	0xbe, 0x52, 0x83, 0x65, 0xf2, 0xda, 0x0f, 0x30, 0x41, 0xcf, 0xbf, 0x14, 0x32, 0x16, 0xdf, 0xd2,
	0x6b, 0x23, 0xde, 0x40, 0x27, 0xe6, 0xb9, 0xcc, 0xc4, 0x8f, 0x2b, 0x13, 0xac, 0x27, 0xd0, 0x55,
	0xf7, 0xfe, 0x2f, 0x67, 0x91, 0x4a, 0xdd, 0x7e, 0x29, 0xfa, 0xda, 0xa7, 0xb6, 0x72, 0x5f, 0xfe,
	0x09, 0x00, 0x00, 0xff, 0xff, 0x71, 0xe2, 0xe5, 0x9d, 0x24, 0x03, 0x00, 0x00,
}
